name: Lint and test workflow
on:
  workflow_call:

jobs:
  lint_and_test:
    name: Lint and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Use Node.js 16.x
        uses: actions/setup-node@3
        with:
          node-version: 16.x
      - uses: actions/cache@3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test/unit/ci
