name: Build and package apps
on:
  workflow_call:

jobs:
  package:
    name: Package application
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Ls files
        run: ls -R
      - name: Package and publish application
        run: yarn release
        env:
          PLATFORM: ${{ runner.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: forecast_work_${{ runner.os }}
          path: |
            - release/*.exe
            - release/*.deb
            - release/*.apk
            - release/*.dmg
