name: Build and package apps
on:
  workflow_call:

jobs:
  package:
    name: Package application
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Use yarn@latest
        run: >-
          corepack enable;
          corepack prepare yarn@stable --activate;
      - uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Package and publish application
        run: yarn run release
        env:
          PLATFORM: ${{ runner.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forecast_work_${{ runner.os }}
          path: release/*.*
