name: Publish
on:
  workflow_call:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: forecast_work
          path: forecast_work
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            LICENSE
            README.md
            CHANGELOG.md
            *.exe
            *.dmg
            *.apk
            *.deb
