name: Publish
on:
  workflow_call:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: forecast_work_Windows
      - name: Download artifacts (macOS)
        uses: actions/download-artifact@v4
        with:
          name: forecast_work_macOS
      - name: Download artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: forecast_work_Linux
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            LICENSE
            README.md
            CHANGELOG.md
            *.exe
            *.dmg
            *.apk
            *.deb
